// Realistic mock data for development — Unsplash photos via CDN
const U = (id, w = 800, h = 600) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&h=${h}&fit=crop&auto=format&q=80`

const AVA = (id) => U(id, 200, 200)

export const mockHosts = [
  {
    id: 'h1',
    full_name: 'Sofia Gallo',
    avatar_url: AVA('1494790108377-be9c29b29330'),
    bio: 'Architetta e amante delle serate lente. Nata a Napoli, vivo a Milano da 8 anni. Credo che le connessioni vere nascano solo rallentando.',
    city: 'Milano',
    is_verified: true,
    rating: 4.9,
    experience_count: 47,
    completed_bookings: 47,
    joined: '2023-03',
    reputation_tiers: ['founding_member', 'top_host'],
  },
  {
    id: 'h2',
    full_name: 'Marco Ferrante',
    avatar_url: AVA('1500648767791-00dcc994a43e'),
    bio: 'Runner seriale e appassionato di caffè specialty. Porto persone a scoprire i parchi nascosti della città all\'alba.',
    city: 'Roma',
    is_verified: true,
    rating: 4.8,
    experience_count: 31,
    completed_bookings: 31,
    joined: '2023-06',
    reputation_tiers: ['trusted_explorer', 'top_host'],
  },
  {
    id: 'h3',
    full_name: 'Elena Ricci',
    avatar_url: AVA('1438761681033-6461ffad8d80'),
    bio: 'Sommelier e appassionata di cinema d\'autore. Credo che un buon film vada vissuto in compagnia, non in solitudine.',
    city: 'Firenze',
    is_verified: true,
    rating: 5.0,
    experience_count: 22,
    completed_bookings: 22,
    joined: '2023-09',
    reputation_tiers: ['top_host', 'city_leader'],
  },
  {
    id: 'h4',
    full_name: 'Luca Marini',
    avatar_url: AVA('1472099645785-5658abf4ff4e'),
    bio: 'Chef autodidatta. Ogni domenica mattina cucino ricette di mia nonna con chi vuole imparare. Il cibo è emozione.',
    city: 'Bologna',
    is_verified: false,
    rating: 4.7,
    experience_count: 18,
    completed_bookings: 18,
    joined: '2024-01',
    reputation_tiers: [],
  },
  {
    id: 'h5',
    full_name: 'Chiara Lombardi',
    avatar_url: AVA('1534528741775-53994a69daeb'),
    bio: 'Musicista e insegnante di yoga. Organizzo sessioni di lettura silenziosa in biblioteca e aperitivi musicali in terrazza.',
    city: 'Torino',
    is_verified: true,
    rating: 4.9,
    experience_count: 35,
    completed_bookings: 35,
    joined: '2023-04',
    reputation_tiers: ['top_host', 'trusted_explorer'],
  },
]

export const mockReviews = {
  exp1: [
    { id: 'r1', reviewer: { name: 'Andrea M.', avatar: AVA('1507003211169-0a1dd7228f2d') }, rating: 5, comment: 'Vista incredibile, Sofia è stata una padrona di casa perfetta. Ho fatto amicizia con gli altri partecipanti.', date: '2024-05-20' },
    { id: 'r2', reviewer: { name: 'Giulia P.', avatar: AVA('1438761681033-6461ffad8d80') }, rating: 5, comment: 'Un aperitivo diverso da tutti gli altri. La terrazza è esattamente come nelle foto. Da rifare.', date: '2024-05-14' },
    { id: 'r3', reviewer: { name: 'Thomas K.', avatar: AVA('1500648767791-00dcc994a43e') }, rating: 5, comment: 'I was visiting Milan for work and this was the highlight of my trip. Genuine and warm.', date: '2024-05-08' },
  ],
  exp2: [
    { id: 'r4', reviewer: { name: 'Sara V.', avatar: AVA('1534528741775-53994a69daeb') }, rating: 5, comment: 'Marco conosce ogni angolo di Roma. Abbiamo corso per un\'ora ma sembrava un gioco.', date: '2024-05-22' },
    { id: 'r5', reviewer: { name: 'Filippo R.', avatar: AVA('1472099645785-5658abf4ff4e') }, rating: 4, comment: 'Ottimo ritmo, percorso bellissimo. Il caffè post-corsa era eccellente.', date: '2024-05-16' },
  ],
}

export const mockExperiences = [
  {
    id: 'exp1',
    title: 'Aperitivo al tramonto sulla mia terrazza',
    category: 'aperitivo',
    description: 'Vivo al 6° piano a Porta Venezia con una vista mozzafiato sul Duomo. Ogni venerdì apro la terrazza per un aperitivo — spritz fatti in casa, formaggi locali e conversazione vera con persone che non ho mai incontrato. Max 4 persone perché resti intimo e autentico.\n\nNon è un evento organizzato. È il mio modo di conoscere gente nuova. Porta qualcosa da bere se vuoi, oppure no.',
    duration: 120,
    max_participants: 4,
    price: 22,
    city: 'Milano',
    neighborhood: 'Porta Venezia',
    lat: 45.474,
    lng: 9.208,
    photos: [
      U('1567016432779-094069958ea5'),
      U('1414235077428-338989a2e8c0'),
      U('1470337458703-6126592350e4'),
    ],
    host: mockHosts[0],
    rating: 4.9,
    review_count: 31,
    distance: 0.8,
    available_dates: ['2024-06-15', '2024-06-21', '2024-06-28'],
    reviews: mockReviews.exp1,
  },
  {
    id: 'exp2',
    title: 'Running all\'alba nei parchi nascosti di Roma',
    category: 'run',
    description: 'Ti porto a scoprire la Roma che i turisti non vedono mai — parchi silenziosi, fontane dimenticate, panorami segreti. Corriamo 8km a ritmo tranquillo, poi colazione con il miglior caffè del quartiere.\n\nNessun livello richiesto. Basta svegliarsi presto e avere voglia di scoprire qualcosa di nuovo.',
    duration: 90,
    max_participants: 3,
    price: 18,
    city: 'Roma',
    neighborhood: 'Prati',
    lat: 41.903,
    lng: 12.457,
    photos: [
      U('1552674605-db6ffd4facb5'),
      U('1476480862126-209bfaa8edc8'),
    ],
    host: mockHosts[1],
    rating: 4.8,
    review_count: 19,
    distance: 1.2,
    available_dates: ['2024-06-10', '2024-06-12', '2024-06-14'],
    reviews: mockReviews.exp2,
  },
  {
    id: 'exp3',
    title: 'Serata cinema d\'autore nel mio salotto',
    category: 'cinema',
    description: 'Sono sommelier e appassionata di cinema d\'autore. Una volta al mese invito 3 persone a guardare un film nel mio salotto — grande schermo, audio cinema, vino selezionato che abbino al film.\n\nStasera: Parasite di Bong Joon-ho. Vino coreano e qualche snack. Parliamo del film dopo.',
    duration: 180,
    max_participants: 3,
    price: 30,
    city: 'Firenze',
    neighborhood: 'Oltrarno',
    lat: 43.765,
    lng: 11.246,
    photos: [
      U('1489599849927-2ee91cede3ba'),
      U('1536440136628-849c177e76a1'),
    ],
    host: mockHosts[2],
    rating: 5.0,
    review_count: 14,
    distance: 2.1,
    available_dates: ['2024-06-18', '2024-06-25'],
    reviews: [],
  },
  {
    id: 'exp4',
    title: 'Lezione di pasta fresca con nonna Graziella',
    category: 'cooking',
    description: 'Mia nonna ha 78 anni e fa la pasta fresca da quando ne aveva 12. La domenica mattina, apriamo la cucina per massimo 2 persone. Impariamo a fare tagliatelle e tortellini a mano. Pranziamo insieme quello che abbiamo fatto.',
    duration: 240,
    max_participants: 2,
    price: 45,
    city: 'Bologna',
    neighborhood: 'Bolognina',
    lat: 44.499,
    lng: 11.335,
    photos: [
      U('1556910103-1c02745aae4d'),
      U('1507048233595-1f4c67867fe2'),
    ],
    host: mockHosts[3],
    rating: 4.7,
    review_count: 11,
    distance: 3.4,
    available_dates: ['2024-06-09', '2024-06-16', '2024-06-23'],
    reviews: [],
  },
  {
    id: 'exp5',
    title: 'Lettura silenziosa al Valentino',
    category: 'reading',
    description: 'Ogni sabato mattina porto un libro al Parco del Valentino e leggo per 2 ore. Cerco qualcuno che voglia fare lo stesso, in silenzio, fianco a fianco. Nessuna pressione di parlare, nessun obbligo di interagire. Solo la pace di leggere vicino a un\'altra persona.',
    duration: 120,
    max_participants: 2,
    price: 8,
    city: 'Torino',
    neighborhood: 'Crocetta',
    lat: 45.056,
    lng: 7.685,
    photos: [
      U('1512820790803-83ca734da794'),
      U('1481627834876-b7833e8f5570'),
    ],
    host: mockHosts[4],
    rating: 4.9,
    review_count: 28,
    distance: 0.5,
    available_dates: ['2024-06-08', '2024-06-15', '2024-06-22'],
    reviews: [],
  },
  {
    id: 'exp6',
    title: 'Concerto privato in cortile — chitarra classica',
    category: 'music',
    description: 'Sono un chitarrista classico. Il mio cortile ha un\'acustica straordinaria. Una volta alla settimana suono per 4 persone massimo — 45 minuti di musica, poi aperitivo e chiacchiere. Niente di formale, niente di pretenzioso.',
    duration: 90,
    max_participants: 4,
    price: 25,
    city: 'Milano',
    neighborhood: 'Navigli',
    lat: 45.448,
    lng: 9.172,
    photos: [
      U('1511671782779-c97d3d27a1d4'),
      U('1493225457124-a3eb161ffa5f'),
    ],
    host: {
      id: 'h6',
      full_name: 'Roberto Esposito',
      avatar_url: AVA('1507003211169-0a1dd7228f2d'),
      bio: 'Chitarrista classico e insegnante. Vivo nei Navigli da sempre.',
      city: 'Milano',
      is_verified: true,
      rating: 4.8,
      experience_count: 24,
      joined: '2023-11',
    },
    rating: 4.8,
    review_count: 17,
    distance: 1.9,
    available_dates: ['2024-06-11', '2024-06-18'],
    reviews: [],
  },
]

export const mockBookings = [
  {
    id: 'b1',
    experience: mockExperiences[0],
    status: 'confirmed',
    starts_at: '2024-06-15T18:30:00',
    participants: 2,
    total_price: 44,
    meeting_point: 'Ingresso principale di Via Melzo 14 — citofono Gallo',
    meeting_lat: 45.474,
    meeting_lng: 9.208,
    unread_messages: 2,
  },
  {
    id: 'b2',
    experience: mockExperiences[4],
    status: 'pending',
    starts_at: '2024-06-22T10:00:00',
    participants: 1,
    total_price: 8,
    meeting_point: null,
    unread_messages: 0,
  },
  {
    id: 'b3',
    experience: mockExperiences[1],
    status: 'completed',
    starts_at: '2024-05-18T06:30:00',
    participants: 1,
    total_price: 18,
    meeting_point: 'Fontana dei Tritoni — lato nord',
    meeting_lat: 41.900,
    meeting_lng: 12.477,
    unread_messages: 0,
  },
]

export const mockMessages = {
  b1: [
    { id: 'm1', sender_id: 'h1', content: 'Ciao! Sono felice che parteciperai venerdì. Hai qualche allergia alimentare che dovrei sapere?', created_at: '2024-06-10T14:23:00', is_read: true },
    { id: 'm2', sender_id: 'me', content: 'Nessuna allergia! Non vedo l\'ora. Posso portare qualcosa?', created_at: '2024-06-10T15:01:00', is_read: true },
    { id: 'm3', sender_id: 'h1', content: 'Magari una bottiglia di vino bianco se vuoi — ma non è obbligatorio. A venerdì!', created_at: '2024-06-10T15:34:00', is_read: false },
    { id: 'm4', sender_id: 'h1', content: 'Oh, e il punto d\'incontro è l\'ingresso al citofono Gallo. Ti mando un pin.', created_at: '2024-06-10T15:35:00', is_read: false },
  ],
}

export const mockNotifications = [
  { id: 'n1', type: 'booking_confirmed', title: 'Prenotazione confermata', body: 'Sofia ha confermato il tuo aperitivo per venerdì 15 giugno', is_read: false, created_at: '2024-06-10T10:00:00' },
  { id: 'n2', type: 'new_message', title: 'Nuovo messaggio da Sofia', body: 'Magari una bottiglia di vino bianco se vuoi...', is_read: false, created_at: '2024-06-10T15:35:00' },
  { id: 'n3', type: 'review_received', title: 'Nuova recensione', body: 'Andrea M. ha lasciato 5 stelle per la tua esperienza', is_read: true, created_at: '2024-06-08T18:00:00' },
  { id: 'n4', type: 'booking_request', title: 'Nuova richiesta', body: 'Thomas K. vuole partecipare al tuo aperitivo', is_read: true, created_at: '2024-06-07T11:30:00' },
]

export const mockUser = {
  id: 'me',
  full_name: 'Alessio Romano',
  avatar_url: AVA('1507003211169-0a1dd7228f2d'),
  bio: 'Curioso per natura. Amo le conversazioni vere e le esperienze che lasciano qualcosa.',
  city: 'Milano',
  is_verified: false,
  email: 'alessio@example.com',
  role: 'both',
  lat: 45.462,
  lng: 9.190,
  reputation_tiers: ['trusted_explorer'],
  completed_bookings: 1,
  social_wallet_balance: 180,
  referral_code: 'ALESSIO24',
  referral_count: 3,
}

export const mockWalletTransactions = [
  { id: 'w1', type: 'earned', amount: 50, label: 'Prima prenotazione completata', date: '2024-05-18' },
  { id: 'w2', type: 'earned', amount: 30, label: 'Referral: Marco T.', date: '2024-05-22' },
  { id: 'w3', type: 'earned', amount: 50, label: 'Referral: Sara V.', date: '2024-06-01' },
  { id: 'w4', type: 'spent', amount: -30, label: 'Sconto su Aperitivo Sofia', date: '2024-06-10' },
  { id: 'w5', type: 'earned', amount: 80, label: 'Bonus Trusted Explorer', date: '2024-06-11' },
]
